name: Run Batch Export Tests

on:
  pull_request:
    # Trigger when files under the templates/ directory are modified
    paths:
      - 'templates/**'

jobs:
  batch-export-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run batch export metadata tests
        run: |
          poetry run pytest batch_export_tests/metadata_tests.py